/**
 * rive-writer.ts
 *
 * The original repository claimed to emit valid `.riv` binaries. That claim was
 * not verifiable from the available public tooling or from any runtime/editor
 * validation included in the repository. The supported pipeline therefore does
 * not emit `.riv` files.
 *
 * The low-level byte utilities remain because they are small, testable, and
 * still useful if a future validated writer is introduced.
 */

export interface ExperimentalRiveWriterStatus {
  supported: false;
  reason: string;
  limitations: string[];
}

export function encodeVarint(value: number): Uint8Array {
  if (!Number.isFinite(value) || value < 0) {
    throw new Error(
      `encodeVarint expects a non-negative finite number, got ${value}`,
    );
  }

  const bytes: number[] = [];
  let current = Math.floor(value) >>> 0;
  do {
    let byte = current & 0x7f;
    current >>>= 7;
    if (current !== 0) {
      byte |= 0x80;
    }
    bytes.push(byte);
  } while (current !== 0);

  return new Uint8Array(bytes);
}

export class BinaryWriter {
  private readonly chunks: Uint8Array[] = [];
  private totalLength = 0;

  get byteLength(): number {
    return this.totalLength;
  }

  writeByte(value: number): void {
    this.writeBytes(new Uint8Array([value & 0xff]));
  }

  writeBytes(bytes: Uint8Array): void {
    this.chunks.push(bytes);
    this.totalLength += bytes.length;
  }

  writeVarint(value: number): void {
    this.writeBytes(encodeVarint(value));
  }

  writeFloat32(value: number): void {
    const buffer = new ArrayBuffer(4);
    new DataView(buffer).setFloat32(0, value, true);
    this.writeBytes(new Uint8Array(buffer));
  }

  writeUint32(value: number): void {
    const buffer = new ArrayBuffer(4);
    new DataView(buffer).setUint32(0, value >>> 0, true);
    this.writeBytes(new Uint8Array(buffer));
  }

  writeString(value: string): void {
    const encoded = new TextEncoder().encode(value);
    this.writeVarint(encoded.length);
    this.writeBytes(encoded);
  }

  toUint8Array(): Uint8Array {
    const result = new Uint8Array(this.totalLength);
    let offset = 0;
    for (const chunk of this.chunks) {
      result.set(chunk, offset);
      offset += chunk.length;
    }
    return result;
  }
}

export function getRiveWriterStatus(): ExperimentalRiveWriterStatus {
  return {
    supported: false,
    reason:
      'Validated `.riv` generation is disabled. The original hand-written binary writer was incomplete and unverified against a supported public authoring or compiler workflow.',
    limitations: [
      'No editor or runtime validation was included in this repository to prove the generated bytes loaded correctly.',
      'Schema coverage for meshes, bones, assets, animations, and state machines was incomplete and partially guessed.',
      'The current supported export path is a `.rivebundle` intermediate with JSON IR, SVG previews, and masked PNG assets.',
    ],
  };
}
