/**
 * rive-binary-writer.ts
 *
 * Isolated `.riv` binary file writer for the image-to-rive pipeline.
 *
 * Module boundaries (enforced by convention):
 *   - Imports byte utilities from: rive-writer.ts
 *   - Imports format constants from: rive-format-defs.ts
 *   - Type-only imports from: pipeline/contracts.ts (pure interfaces, no logic)
 *   - No imports from pipeline stage modules, runtime helpers, or CLI
 *   - No shared mutable state with the .rivebundle export path
 *
 * Status: Phase 3 (Animation — Gate 1 complete, Gate 2 in progress).
 *   - Public API is defined and stable.
 *   - writeRiveFile() writes a complete object graph with animations.
 *   - Generated bytes are theoretically loadable by Rive runtime but not yet
 *     verified by an automated harness (Gate 2).
 *
 * Phase roadmap:
 *   Phase 1 (complete): API isolation + header stub
 *   Phase 2 (complete): Static content — Backboard, Artboard, Image, Mesh, MeshVertex, Bone, Skin
 *   Phase 3 (this file): Animation — LinearAnimation, KeyedObject, KeyedProperty, KeyFrameDouble
 *   Phase 4: Verification harness — runtime load testing via Rive WASM
 */

import type {
  ComponentAnimationPlan,
  PoseBone,
  PoseComponent,
  PoseResult,
  SegComponent,
  SegMesh,
  SegMeshVertex,
  SegResult,
} from './pipeline/contracts.js';
import type { RivePropertyDef } from './rive-format-defs.js';

import {
  PROPERTY_BY_KEY,
  RIVE_MAGIC,
  RIVE_MAJOR_VERSION,
  RIVE_MINOR_VERSION,
  RiveInterpolationType,
  RivePropertyKey,
  RiveTypeKey,
  TocBackingType,
} from './rive-format-defs.js';
import { BinaryWriter } from './rive-writer.js';

// ---------------------------------------------------------------------------
// Public API version
// ---------------------------------------------------------------------------

/**
 * Semantic version of the rive-binary-writer module.
 * Consumers may check this to confirm which phase of the writer is active.
 *
 * Phase 1 = '0.1.0' (header stub, no loadable output)
 * Phase 2 = '0.2.0' (static content, theoretically loadable)
 * Phase 3 = '0.3.0' (animation support)
 */
export const RIVE_BINARY_WRITER_VERSION = '0.4.0';

// ---------------------------------------------------------------------------
// Input / output types
// ---------------------------------------------------------------------------

/**
 * Pipeline IR input consumed by the `.riv` writer.
 *
 * All fields mirror the pipeline stage output types and are intentionally
 * read-only to prevent accidental mutation of shared pipeline state.
 * The writer must NOT modify any of these objects.
 */
export interface RiveWriterInput {
  /** Segmentation output from the run-segmentation stage. */
  readonly segResult: SegResult;
  /** Pose estimation output from the run-pose stage. */
  readonly poseResult: PoseResult;
  /** Animation plans from the generate-animation stage. */
  readonly animationPlans: ReadonlyArray<ComponentAnimationPlan>;
  /**
   * Optional artboard width override in pixels.
   * When omitted, per-component dimensions from segResult are used.
   * Max: 8192 (MAX_ARTBOARD_DIMENSION).
   */
  readonly artboardWidth?: number;
  /**
   * Optional artboard height override in pixels.
   * When omitted, per-component dimensions from segResult are used.
   * Max: 8192 (MAX_ARTBOARD_DIMENSION).
   */
  readonly artboardHeight?: number;
}

/**
 * Result returned by writeRiveFile().
 *
 * The `bytes` field contains the encoded content. In Phase 2 this is a
 * complete static object graph that should be loadable by the Rive runtime,
 * though it has not yet been verified by an automated harness (Gate 2).
 */
export interface RiveWriterResult {
  /**
   * Encoded binary content.
   * Phase 1: header stub only (not loadable).
   * Phase 2+: full static object graph (theoretically loadable).
   * Phase 3+: includes animation data.
   */
  readonly bytes: Uint8Array;
  /**
   * Number of artboards derived from the input segmentation result.
   * Matches input.segResult.components.length.
   */
  readonly artboardCount: number;
  /**
   * Total bone count across all pose components.
   * Computed by summing bones from every PoseComponent.skeleton.bones.
   */
  readonly boneCount: number;
  /**
   * Non-fatal warnings generated during encoding.
   * Phase 1: contained stub notice.
   * Phase 2+: populated on schema coverage gaps or unsupported features.
   */
  readonly warnings: readonly string[];
}

// ---------------------------------------------------------------------------
// Internal types for encoding
// ---------------------------------------------------------------------------

interface EncodedObject {
  readonly typeKey: number;
  readonly id: number;
  readonly bytes: Uint8Array;
  readonly propertyKeys: ReadonlySet<number>;
}

interface EncodingContext {
  readonly objects: EncodedObject[];
  readonly warnings: string[];
  nextId: number;
}

interface ArtboardLocalState {
  nextId: number;
  readonly boneIdMap: Map<string, number>;
}

// ---------------------------------------------------------------------------
// Property encoding helpers
// ---------------------------------------------------------------------------

function writePropertyValue(
  w: BinaryWriter,
  prop: RivePropertyDef,
  value: number | string | boolean | Uint8Array,
): void {
  w.writeVarint(prop.key);

  switch (prop.backingType) {
    case TocBackingType.Uint:
      w.writeVarint(
        typeof value === 'boolean'
          ? value
            ? 1
            : 0
          : typeof value === 'number'
            ? value
            : Number(value),
      );
      break;
    case TocBackingType.String:
      if (value instanceof Uint8Array) {
        w.writeVarint(value.length);
        w.writeBytes(value);
      } else {
        w.writeString(String(value));
      }
      break;
    case TocBackingType.Float:
      w.writeFloat32(Number(value));
      break;
    case TocBackingType.Color:
      w.writeUint32(Number(value));
      break;
    default:
      throw new Error(`Unknown backing type: ${prop.backingType}`);
  }
}

function allocateArtboardLocalId(state: ArtboardLocalState): number {
  const id = state.nextId;
  state.nextId += 1;
  return id;
}

// ---------------------------------------------------------------------------
// Object encoders
// ---------------------------------------------------------------------------

function encodeBackboard(ctx: EncodingContext): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  // Backboard has no properties in the minimal case
  // (It inherits from nothing and has no required fields)

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>();

  return { typeKey: RiveTypeKey.Backboard, id, bytes, propertyKeys };
}

function encodeArtboard(
  ctx: EncodingContext,
  component: SegComponent,
  width: number,
  height: number,
): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  // LayoutComponent properties (inherited)
  writePropertyValue(w, RivePropertyKey.width, width);
  writePropertyValue(w, RivePropertyKey.height, height);
  writePropertyValue(w, RivePropertyKey.layout_clip, 0); // No clipping

  // Artboard-specific properties
  writePropertyValue(w, RivePropertyKey.artboard_originX, width / 2);
  writePropertyValue(w, RivePropertyKey.artboard_originY, height / 2);

  // Component properties
  writePropertyValue(w, RivePropertyKey.name, component.label || component.id);
  writePropertyValue(w, RivePropertyKey.parentId, 0); // Parent is Backboard (id 0)

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>([
    RivePropertyKey.width.key,
    RivePropertyKey.height.key,
    RivePropertyKey.layout_clip.key,
    RivePropertyKey.artboard_originX.key,
    RivePropertyKey.artboard_originY.key,
    RivePropertyKey.name.key,
    RivePropertyKey.parentId.key,
  ]);

  return { typeKey: RiveTypeKey.Artboard, id, bytes, propertyKeys };
}

function encodeImage(
  ctx: EncodingContext,
  component: SegComponent,
  parentId: number,
): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  // Image properties
  writePropertyValue(
    w,
    RivePropertyKey.image_originX,
    component.image_size.w / 2,
  );
  writePropertyValue(
    w,
    RivePropertyKey.image_originY,
    component.image_size.h / 2,
  );

  // Component properties (Drawable -> Node -> TransformComponent -> ... -> Component)
  writePropertyValue(
    w,
    RivePropertyKey.name,
    `${component.label || 'image'}_instance`,
  );
  writePropertyValue(w, RivePropertyKey.parentId, parentId);

  // Drawable blend mode
  writePropertyValue(w, RivePropertyKey.blendModeValue, 3); // SrcOver

  // WorldTransformComponent opacity
  writePropertyValue(w, RivePropertyKey.opacity, 1.0);

  // TransformComponent properties
  writePropertyValue(w, RivePropertyKey.rotation, 0);
  writePropertyValue(w, RivePropertyKey.scaleX, 1);
  writePropertyValue(w, RivePropertyKey.scaleY, 1);

  // Node position
  writePropertyValue(w, RivePropertyKey.node_x, component.image_size.w / 2);
  writePropertyValue(w, RivePropertyKey.node_y, component.image_size.h / 2);

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>([
    RivePropertyKey.image_originX.key,
    RivePropertyKey.image_originY.key,
    RivePropertyKey.name.key,
    RivePropertyKey.parentId.key,
    RivePropertyKey.blendModeValue.key,
    RivePropertyKey.opacity.key,
    RivePropertyKey.rotation.key,
    RivePropertyKey.scaleX.key,
    RivePropertyKey.scaleY.key,
    RivePropertyKey.node_x.key,
    RivePropertyKey.node_y.key,
  ]);

  return { typeKey: RiveTypeKey.Image, id, bytes, propertyKeys };
}

function encodeMeshVertex(
  ctx: EncodingContext,
  vertex: SegMeshVertex,
  parentId: number,
): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  // Vertex position
  writePropertyValue(w, RivePropertyKey.vertex_x, vertex.x);
  writePropertyValue(w, RivePropertyKey.vertex_y, vertex.y);

  // MeshVertex UV coordinates
  writePropertyValue(w, RivePropertyKey.meshVertex_u, vertex.u);
  writePropertyValue(w, RivePropertyKey.meshVertex_v, vertex.v);
  writePropertyValue(w, RivePropertyKey.parentId, parentId);

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>([
    RivePropertyKey.vertex_x.key,
    RivePropertyKey.vertex_y.key,
    RivePropertyKey.meshVertex_u.key,
    RivePropertyKey.meshVertex_v.key,
    RivePropertyKey.parentId.key,
  ]);

  return { typeKey: RiveTypeKey.MeshVertex, id, bytes, propertyKeys };
}

function encodeTriangleIndexBytes(
  mesh: SegMesh,
  vertexCount: number,
): Uint8Array {
  const writer = new BinaryWriter();
  const maxVertexIndex = vertexCount - 1;

  for (const tri of mesh.triangles) {
    for (const index of tri) {
      if (!Number.isInteger(index) || index < 0 || index > maxVertexIndex) {
        throw new Error(
          `Mesh triangle index ${index} is out of bounds for ${vertexCount} vertices.`,
        );
      }
      writer.writeVarint(index);
    }
  }

  return writer.toUint8Array();
}

function encodeMesh(
  ctx: EncodingContext,
  mesh: SegMesh,
  vertexCount: number,
  parentId: number,
): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  const triangleBytes = encodeTriangleIndexBytes(mesh, vertexCount);
  writePropertyValue(w, RivePropertyKey.triangleIndexBytes, triangleBytes);

  // Component properties
  writePropertyValue(w, RivePropertyKey.name, 'mesh');
  writePropertyValue(w, RivePropertyKey.parentId, parentId);

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>([
    RivePropertyKey.triangleIndexBytes.key,
    RivePropertyKey.name.key,
    RivePropertyKey.parentId.key,
  ]);

  return { typeKey: RiveTypeKey.Mesh, id, bytes, propertyKeys };
}

function encodeBone(
  ctx: EncodingContext,
  bone: PoseBone,
  parentId: number,
): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  // Bone is not a RootBone, so use regular Bone encoding
  // SkeletalComponent -> TransformComponent -> WorldTransformComponent -> ContainerComponent -> Component

  // Component properties
  writePropertyValue(w, RivePropertyKey.name, bone.name);
  writePropertyValue(w, RivePropertyKey.parentId, parentId);

  // TransformComponent properties
  writePropertyValue(w, RivePropertyKey.rotation, bone.rotation);
  writePropertyValue(w, RivePropertyKey.scaleX, 1);
  writePropertyValue(w, RivePropertyKey.scaleY, 1);

  // WorldTransformComponent opacity
  writePropertyValue(w, RivePropertyKey.opacity, 1.0);

  // Bone-specific properties
  writePropertyValue(w, RivePropertyKey.bone_length, bone.length);

  // Note: Bone position is determined by parent connection in Rive
  // The actual x/y of the bone tip would be calculated from rotation and length

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>([
    RivePropertyKey.name.key,
    RivePropertyKey.parentId.key,
    RivePropertyKey.rotation.key,
    RivePropertyKey.scaleX.key,
    RivePropertyKey.scaleY.key,
    RivePropertyKey.opacity.key,
    RivePropertyKey.bone_length.key,
  ]);

  return { typeKey: RiveTypeKey.Bone, id, bytes, propertyKeys };
}

function encodeRootBone(
  ctx: EncodingContext,
  bone: PoseBone,
  parentId: number,
): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  // RootBone inherits from Bone

  // Component properties
  writePropertyValue(w, RivePropertyKey.name, bone.name);
  writePropertyValue(w, RivePropertyKey.parentId, parentId);

  // TransformComponent properties
  writePropertyValue(w, RivePropertyKey.rotation, bone.rotation);
  writePropertyValue(w, RivePropertyKey.scaleX, 1);
  writePropertyValue(w, RivePropertyKey.scaleY, 1);

  // WorldTransformComponent opacity
  writePropertyValue(w, RivePropertyKey.opacity, 1.0);

  // Bone properties
  writePropertyValue(w, RivePropertyKey.bone_length, bone.length);

  // RootBone-specific position
  writePropertyValue(w, RivePropertyKey.rootBone_x, bone.x);
  writePropertyValue(w, RivePropertyKey.rootBone_y, bone.y);

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>([
    RivePropertyKey.name.key,
    RivePropertyKey.parentId.key,
    RivePropertyKey.rotation.key,
    RivePropertyKey.scaleX.key,
    RivePropertyKey.scaleY.key,
    RivePropertyKey.opacity.key,
    RivePropertyKey.bone_length.key,
    RivePropertyKey.rootBone_x.key,
    RivePropertyKey.rootBone_y.key,
  ]);

  return { typeKey: RiveTypeKey.RootBone, id, bytes, propertyKeys };
}

function encodeSkin(ctx: EncodingContext, parentId: number): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  // Skin transform matrix (identity for now)
  writePropertyValue(w, RivePropertyKey.skin_xx, 1.0);
  writePropertyValue(w, RivePropertyKey.skin_yx, 0.0);
  writePropertyValue(w, RivePropertyKey.skin_xy, 0.0);
  writePropertyValue(w, RivePropertyKey.skin_yy, 1.0);
  writePropertyValue(w, RivePropertyKey.skin_tx, 0.0);
  writePropertyValue(w, RivePropertyKey.skin_ty, 0.0);

  // Component properties
  writePropertyValue(w, RivePropertyKey.name, 'skin');
  writePropertyValue(w, RivePropertyKey.parentId, parentId);

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>([
    RivePropertyKey.skin_xx.key,
    RivePropertyKey.skin_yx.key,
    RivePropertyKey.skin_xy.key,
    RivePropertyKey.skin_yy.key,
    RivePropertyKey.skin_tx.key,
    RivePropertyKey.skin_ty.key,
    RivePropertyKey.name.key,
    RivePropertyKey.parentId.key,
  ]);

  return { typeKey: RiveTypeKey.Skin, id, bytes, propertyKeys };
}

// ---------------------------------------------------------------------------
// Phase 3: Animation object encoders
// ---------------------------------------------------------------------------

function encodeLinearAnimation(
  ctx: EncodingContext,
  animDef: {
    name: string;
    fps: number;
    durationFrames: number;
    loopType: number;
  },
): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  // LinearAnimation properties
  writePropertyValue(w, RivePropertyKey.fps, animDef.fps);
  writePropertyValue(w, RivePropertyKey.duration, animDef.durationFrames);
  writePropertyValue(w, RivePropertyKey.speed, 1.0); // Normal playback speed
  writePropertyValue(w, RivePropertyKey.loopValue, animDef.loopType);
  writePropertyValue(w, RivePropertyKey.workStart, 0);
  writePropertyValue(w, RivePropertyKey.workEnd, animDef.durationFrames);
  writePropertyValue(w, RivePropertyKey.enableWorkArea, 0); // Disabled

  writePropertyValue(w, RivePropertyKey.animation_name, animDef.name);

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>([
    RivePropertyKey.fps.key,
    RivePropertyKey.duration.key,
    RivePropertyKey.speed.key,
    RivePropertyKey.loopValue.key,
    RivePropertyKey.workStart.key,
    RivePropertyKey.workEnd.key,
    RivePropertyKey.enableWorkArea.key,
    RivePropertyKey.animation_name.key,
  ]);

  return { typeKey: RiveTypeKey.LinearAnimation, id, bytes, propertyKeys };
}

function encodeKeyedObject(
  ctx: EncodingContext,
  objectId: number,
): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  // KeyedObject properties
  writePropertyValue(w, RivePropertyKey.objectId, objectId);

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>([RivePropertyKey.objectId.key]);

  return { typeKey: RiveTypeKey.KeyedObject, id, bytes, propertyKeys };
}

function encodeKeyedProperty(
  ctx: EncodingContext,
  propertyKey: number,
): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  // KeyedProperty properties
  writePropertyValue(w, RivePropertyKey.propertyKey, propertyKey);

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>([RivePropertyKey.propertyKey.key]);

  return { typeKey: RiveTypeKey.KeyedProperty, id, bytes, propertyKeys };
}

function encodeKeyFrameDouble(
  ctx: EncodingContext,
  frame: number,
  value: number,
  interpolationType: number,
  interpolatorId: number | null,
): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  // KeyFrame properties (from KeyFrame parent)
  writePropertyValue(w, RivePropertyKey.frame, frame);

  // InterpolatingKeyFrame properties
  writePropertyValue(w, RivePropertyKey.interpolationType, interpolationType);
  if (interpolatorId !== null) {
    writePropertyValue(w, RivePropertyKey.interpolatorId, interpolatorId);
  }

  // KeyFrameDouble properties
  writePropertyValue(w, RivePropertyKey.keyFrameDouble_value, value);

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>([
    RivePropertyKey.frame.key,
    RivePropertyKey.interpolationType.key,
    ...(interpolatorId !== null ? [RivePropertyKey.interpolatorId.key] : []),
    RivePropertyKey.keyFrameDouble_value.key,
  ]);

  return { typeKey: RiveTypeKey.KeyFrameDouble, id, bytes, propertyKeys };
}

function encodeCubicInterpolator(
  ctx: EncodingContext,
  x1: number,
  y1: number,
  x2: number,
  y2: number,
): EncodedObject {
  const w = new BinaryWriter();
  const id = ctx.nextId++;

  // CubicInterpolator properties
  writePropertyValue(w, RivePropertyKey.cubicX1, x1);
  writePropertyValue(w, RivePropertyKey.cubicY1, y1);
  writePropertyValue(w, RivePropertyKey.cubicX2, x2);
  writePropertyValue(w, RivePropertyKey.cubicY2, y2);

  const bytes = w.toUint8Array();
  const propertyKeys = new Set<number>([
    RivePropertyKey.cubicX1.key,
    RivePropertyKey.cubicY1.key,
    RivePropertyKey.cubicX2.key,
    RivePropertyKey.cubicY2.key,
  ]);

  return { typeKey: RiveTypeKey.CubicInterpolator, id, bytes, propertyKeys };
}

/**
 * Encode animations from a component animation plan.
 * Creates: LinearAnimation → KeyedObject → KeyedProperty → KeyFrameDouble for each animation
 */
function encodeAnimation(
  ctx: EncodingContext,
  componentId: string,
  animPlan: ComponentAnimationPlan,
  localState: ArtboardLocalState,
): void {
  for (const animDef of animPlan.animations) {
    const linearAnim = encodeLinearAnimation(ctx, animDef);
    ctx.objects.push(linearAnim);

    const needsCubicInterpolator = animDef.tracks.some((track) =>
      track.keyframes.some(
        (keyframe) =>
          (keyframe.interp ?? RiveInterpolationType.Linear) ===
          RiveInterpolationType.Cubic,
      ),
    );

    let cubicInterpolatorObjectId: number | null = null;
    if (needsCubicInterpolator) {
      cubicInterpolatorObjectId = allocateArtboardLocalId(localState);
      const cubicInterpolator = encodeCubicInterpolator(ctx, 0.42, 0, 0.58, 1);
      ctx.objects.push(cubicInterpolator);
    }

    const tracksByBone = new Map<string, (typeof animDef.tracks)[number][]>();
    for (const track of animDef.tracks) {
      if (!tracksByBone.has(track.boneName)) {
        tracksByBone.set(track.boneName, []);
      }
      tracksByBone.get(track.boneName)!.push(track);
    }

    for (const [boneName, tracks] of tracksByBone) {
      const boneObjectId = localState.boneIdMap.get(boneName);

      if (boneObjectId === undefined) {
        ctx.warnings.push(
          `Animation "${animDef.name}": Bone "${boneName}" not found in component ${componentId}`,
        );
        continue;
      }

      const keyedObject = encodeKeyedObject(ctx, boneObjectId);
      ctx.objects.push(keyedObject);

      for (const track of tracks) {
        const rivePropertyKey = getRivePropertyKey(track.property);
        const keyedProp = encodeKeyedProperty(ctx, rivePropertyKey);
        ctx.objects.push(keyedProp);

        for (const kf of track.keyframes) {
          const interpolationType = kf.interp ?? RiveInterpolationType.Linear;
          const interpolatorId =
            interpolationType === RiveInterpolationType.Cubic
              ? cubicInterpolatorObjectId
              : null;
          const keyFrame = encodeKeyFrameDouble(
            ctx,
            kf.frame,
            kf.value,
            interpolationType,
            interpolatorId,
          );
          ctx.objects.push(keyFrame);
        }
      }
    }
  }
}

/**
 * Map animation property names to Rive property keys.
 */
function getRivePropertyKey(prop: string): number {
  switch (prop) {
    case 'x':
      return RivePropertyKey.node_x.key;
    case 'y':
      return RivePropertyKey.node_y.key;
    case 'rotation':
      return RivePropertyKey.rotation.key;
    case 'scaleX':
      return RivePropertyKey.scaleX.key;
    case 'scaleY':
      return RivePropertyKey.scaleY.key;
    default:
      throw new Error(`Unknown animation property: ${prop}`);
  }
}

// ---------------------------------------------------------------------------
// ToC (Table of Contents) generation
// ---------------------------------------------------------------------------

function collectPropertyKeys(objects: EncodedObject[]): Set<number> {
  const keys = new Set<number>();
  for (const obj of objects) {
    for (const key of obj.propertyKeys) {
      keys.add(key);
    }
  }
  return keys;
}

function writeToC(w: BinaryWriter, objects: EncodedObject[]): void {
  const propertyKeys = Array.from(collectPropertyKeys(objects)).sort(
    (a, b) => a - b,
  );

  for (const propertyKey of propertyKeys) {
    w.writeVarint(propertyKey);
  }
  w.writeVarint(0);

  for (let groupStart = 0; groupStart < propertyKeys.length; groupStart += 4) {
    let packedWord = 0;
    for (let offset = 0; offset < 4; offset += 1) {
      const propertyKey = propertyKeys[groupStart + offset];
      if (propertyKey === undefined) {
        continue;
      }

      const def = PROPERTY_BY_KEY.get(propertyKey);
      if (!def) {
        throw new Error(
          `Unknown property key ${propertyKey} while writing ToC.`,
        );
      }

      packedWord |= def.backingType << (offset * 2);
    }
    w.writeUint32(packedWord);
  }
}

// ---------------------------------------------------------------------------
// Object stream writing
// ---------------------------------------------------------------------------

function writeObjectStream(w: BinaryWriter, objects: EncodedObject[]): void {
  for (const obj of objects) {
    // Write type key
    w.writeVarint(obj.typeKey);
    // Write object body
    w.writeBytes(obj.bytes);
    // Write terminator
    w.writeByte(0x00);
  }
}

// ---------------------------------------------------------------------------
// Internal helpers — counting
// ---------------------------------------------------------------------------

function countTotalBones(poseResult: PoseResult): number {
  return poseResult.components.reduce(
    (sum, c) => sum + c.skeleton.bones.length,
    0,
  );
}

// ---------------------------------------------------------------------------
// Component encoding orchestration
// ---------------------------------------------------------------------------

function encodeComponent(
  ctx: EncodingContext,
  segComponent: SegComponent,
  poseComponent: PoseComponent | undefined,
  artboardWidth: number,
  artboardHeight: number,
  animPlan: ComponentAnimationPlan | undefined,
): void {
  const localState: ArtboardLocalState = {
    nextId: 1,
    boneIdMap: new Map(),
  };

  const artboard = encodeArtboard(
    ctx,
    segComponent,
    artboardWidth,
    artboardHeight,
  );
  ctx.objects.push(artboard);

  const artboardLocalId = 0;
  const imageLocalId = allocateArtboardLocalId(localState);
  const image = encodeImage(ctx, segComponent, artboardLocalId);
  ctx.objects.push(image);

  if (segComponent.mesh && segComponent.mesh.vertices.length > 0) {
    const mesh = segComponent.mesh;
    const meshLocalId = allocateArtboardLocalId(localState);
    const meshObj = encodeMesh(ctx, mesh, mesh.vertices.length, imageLocalId);
    ctx.objects.push(meshObj);

    for (const vertex of mesh.vertices) {
      allocateArtboardLocalId(localState);
      const meshVertex = encodeMeshVertex(ctx, vertex, meshLocalId);
      ctx.objects.push(meshVertex);
    }

    allocateArtboardLocalId(localState);
    const skin = encodeSkin(ctx, meshLocalId);
    ctx.objects.push(skin);
  }

  if (poseComponent) {
    const rootBones: PoseBone[] = [];
    const childBones: PoseBone[] = [];

    for (const bone of poseComponent.skeleton.bones) {
      if (bone.parent === null) {
        rootBones.push(bone);
      } else {
        childBones.push(bone);
      }
    }

    for (const bone of rootBones) {
      const rootBoneLocalId = allocateArtboardLocalId(localState);
      const rootBone = encodeRootBone(ctx, bone, artboardLocalId);
      ctx.objects.push(rootBone);
      localState.boneIdMap.set(bone.name, rootBoneLocalId);
    }

    let remaining = [...childBones];
    let lastCount = -1;
    while (remaining.length > 0 && remaining.length !== lastCount) {
      lastCount = remaining.length;
      const stillRemaining: PoseBone[] = [];

      for (const bone of remaining) {
        const parentId = localState.boneIdMap.get(bone.parent!);
        if (parentId !== undefined) {
          const boneLocalId = allocateArtboardLocalId(localState);
          const boneObj = encodeBone(ctx, bone, parentId);
          ctx.objects.push(boneObj);
          localState.boneIdMap.set(bone.name, boneLocalId);
        } else {
          stillRemaining.push(bone);
        }
      }

      remaining = stillRemaining;
    }

    if (remaining.length > 0) {
      ctx.warnings.push(
        `Component ${segComponent.id}: ${remaining.length} bones could not be encoded ` +
          `due to missing parent references: ${remaining.map((b) => b.name).join(', ')}`,
      );
    }

    if (animPlan) {
      encodeAnimation(ctx, segComponent.id, animPlan, localState);
    }
  }
}

// ---------------------------------------------------------------------------
// File structure helpers
// ---------------------------------------------------------------------------

function writeFileHeader(w: BinaryWriter, fileId = 0): void {
  w.writeBytes(RIVE_MAGIC);
  w.writeVarint(RIVE_MAJOR_VERSION);
  w.writeVarint(RIVE_MINOR_VERSION);
  w.writeVarint(fileId);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Write a `.riv` binary file from the pipeline intermediate representation.
 *
 * Phase 3 behaviour:
 *   Writes a complete object graph with animations:
 *     - Backboard (root)
 *     - For each component:
 *       - Artboard
 *       - Image (child of Artboard)
 *       - Mesh + MeshVertices (if mesh data exists)
 *       - Skin (child of Mesh)
 *       - Bones (RootBone + regular Bone hierarchy)
 *       - LinearAnimations (one per animation plan)
 *         - KeyedObjects (one per animated bone)
 *           - KeyedProperties (one per animated property)
 *             - KeyFrameDoubles (one per keyframe)
 *
 *   The ToC is built in two passes:
 *     1. First pass — encode all objects, collecting property keys used
 *     2. Second pass — write ToC with backing types, then object stream
 *
 *   This output is verified by the Gate 2 runtime-load harness in
 *   `pipeline.test.ts` when `RUN_RIVE_GATE2_EXPECT_PASS=1` is enabled.
 *   Full `.riv` product support is still gated by the remaining checklist in
 *   `HANDOVER.md`.
 *
 * @param input  Immutable pipeline IR from segmentation, pose, and animation stages.
 * @returns      Encoded bytes, artboard/bone counts, and any encoding warnings.
 */
export function writeRiveFile(input: RiveWriterInput): RiveWriterResult {
  const warnings: string[] = [];

  // Initialize encoding context
  const ctx: EncodingContext = {
    objects: [],
    warnings,
    nextId: 0,
  };

  // 1. Create Backboard (always id 0)
  ctx.objects.push(encodeBackboard(ctx));

  // 2. Create a map of pose components by id for quick lookup
  const poseComponentMap = new Map<string, PoseComponent>();
  for (const pc of input.poseResult.components) {
    poseComponentMap.set(pc.id, pc);
  }
  // 3. Create a map of animation plans by component id
  const animPlanMap = new Map<string, (typeof input.animationPlans)[number]>();
  for (const ap of input.animationPlans) {
    animPlanMap.set(ap.id, ap);
  }

  // 4. Encode each segmentation component
  for (const segComponent of input.segResult.components) {
    const poseComponent = poseComponentMap.get(segComponent.id);
    const animPlan = animPlanMap.get(segComponent.id);

    // Determine artboard dimensions
    const width = input.artboardWidth ?? segComponent.image_size.w;
    const height = input.artboardHeight ?? segComponent.image_size.h;

    encodeComponent(ctx, segComponent, poseComponent, width, height, animPlan);
  }

  // 5. Build the file
  const w = new BinaryWriter();

  // Write header
  writeFileHeader(w);

  // Write ToC (built from collected property keys)
  writeToC(w, ctx.objects);

  // Write object stream
  writeObjectStream(w, ctx.objects);

  const artboardCount = input.segResult.components.length;
  const boneCount = countTotalBones(input.poseResult);

  return {
    bytes: w.toUint8Array(),
    artboardCount,
    boneCount,
    warnings,
  };
}
